#include <mmio.h>
#include <utils.h>

#define UNIPHIER_SYSCTRL_BASE		0x61840000
#define UNIPHIER_RSTCTRL4		((UNIPHIER_SYSCTRL_BASE) + 0x200c)
#define UNIPHIER_RSTCTRL7		((UNIPHIER_SYSCTRL_BASE) + 0x2018)
#define   UNIPHIER_RSTCTRL7_UMCSB		BIT(16)
#define   UNIPHIER_RSTCTRL7_UMCA2		BIT(10)
#define   UNIPHIER_RSTCTRL7_UMCA1		BIT(9)
#define   UNIPHIER_RSTCTRL7_UMCA0		BIT(8)
#define   UNIPHIER_RSTCTRL7_UMC32		BIT(2)
#define   UNIPHIER_RSTCTRL7_UMC31		BIT(1)
#define   UNIPHIER_RSTCTRL7_UMC30		BIT(0)
#define UNIPHIER_CLKCTRL4		((UNIPHIER_SYSCTRL_BASE) + 0x210c)
#define   UNIPHIER_CLKCTRL4_PERI		BIT(7)
#define UNIPHIER_CLKCTRL7		((UNIPHIER_SYSCTRL_BASE) + 0x2118)
#define   UNIPHIER_CLKCTRL7_UMCSB		BIT(16)
#define   UNIPHIER_CLKCTRL7_UMC32		BIT(2)
#define   UNIPHIER_CLKCTRL7_UMC31		BIT(1)
#define   UNIPHIER_CLKCTRL7_UMC30		BIT(0)

void uniphier_ld11_clk_enable_uart(void)
{
	mmio_setbits_32(UNIPHIER_CLKCTRL4, UNIPHIER_CLKCTRL4_PERI);
}

void uniphier_ld11_clk_enable_dram(void)
{
	mmio_setbits_32(UNIPHIER_RSTCTRL7,
			UNIPHIER_RSTCTRL7_UMC31 | UNIPHIER_RSTCTRL7_UMC30);
	mmio_setbits_32(UNIPHIER_CLKCTRL7,
			UNIPHIER_CLKCTRL7_UMC31 | UNIPHIER_CLKCTRL7_UMC30);
}

void uniphier_ld20_clk_enable_uart(void)
{
	mmio_setbits_32(UNIPHIER_CLKCTRL4, UNIPHIER_CLKCTRL4_PERI);
}

void uniphier_ld20_clk_enable_dram(void)
{
	mmio_setbits_32(UNIPHIER_RSTCTRL7,
			UNIPHIER_RSTCTRL7_UMCSB | UNIPHIER_RSTCTRL7_UMCA2 |
			UNIPHIER_RSTCTRL7_UMCA1 | UNIPHIER_RSTCTRL7_UMCA0 |
			UNIPHIER_RSTCTRL7_UMC32 | UNIPHIER_RSTCTRL7_UMC31 |
			UNIPHIER_RSTCTRL7_UMC30);

	mmio_setbits_32(UNIPHIER_CLKCTRL7,
			UNIPHIER_CLKCTRL7_UMCSB | UNIPHIER_CLKCTRL7_UMC32 |
			UNIPHIER_CLKCTRL7_UMC31 | UNIPHIER_CLKCTRL7_UMC30);
}
